core/urls.py
from django.urls import path

from core.views import (
    IndexView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    ToggleTaskCompletionView
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/<int:pk>/<str:action>/", ToggleTaskCompletionView.as_view(), name="task-toggle-completion"),
]

app_name = "core"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core"))
]

core/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    tag = models.ManyToManyField(
        to=Tag,
        related_name="tasks"
    )

    def __str__(self) -> str:
        return self.content

core/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from core.models import Task, Tag

class IndexView(generic.ListView):
    model = Task
    template_name = "core/index.html"
    context_object_name = "tasks"
    paginate_by = 2

    def get_queryset(self):
        return (
            super().get_queryset()
            .prefetch_related("tag")
            .order_by("is_completed", "-datetime")
        )

class TaskCreateView(generic.CreateView):
    model = Task
    fields = ("content", "deadline", "tag")
    template_name = "core/task_create.html"
    context_object_name = "task"
    success_url = reverse_lazy("core:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = ("content", "deadline", "tag")
    template_name = "core/task_update.html"
    context_object_name = "task"
    success_url = reverse_lazy("core:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "core/task_delete.html"
    context_object_name = "task"
    success_url = reverse_lazy("core:index")


class TagListView(generic.ListView):
    model = Tag
    template_name = "core/tag_list.html"
    context_object_name = "tags"
    paginate_by = 4


class TagCreateView(generic.CreateView):
    model = Tag
    fields = ("name",)
    template_name = "core/tag_create.html"
    context_object_name = "tag"
    success_url = reverse_lazy("core:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = ("name",)
    template_name = "core/tag_update.html"
    context_object_name = "tag"
    success_url = reverse_lazy("core:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "core/tag_delete.html"
    context_object_name = "tag"
    success_url = reverse_lazy("core:tag-list")


class ToggleTaskCompletionView(generic.View):
    def post(self, request: HttpRequest, pk: int, action: str) -> HttpResponseRedirect:
        task = get_object_or_404(Task, pk=pk)
        if action == "complete":
            task.is_completed = True
        elif action == "uncomplete":
            task.is_completed = False
        else:
            return redirect("/")
        task.save()
        return redirect(request.META.get("HTTP_REFERER", "/"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>TODO List</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
</head>
<body>

{% include "includes/sidebar.html" %}

{% block content %}{% endblock %}

{% include "includes/pagination.html" %}

</body>
</html>

templates/core/index.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center ml-5 mt-3 mb-3">
    <h1><strong>TODO List</strong></h1>
    <a href="{% url 'core:task-create' %}" class="btn btn-success mr-5">Create new</a>
  </div>
  {% for task in tasks %}
    <div class="ml-5 mt-5 mb-3">
      <h5><strong>{{ task.content }}</strong>
        {% if not task.is_completed %}
          <span style="color:red">Not done</span>
        {% else %}
          <span style="color:green">Completed</span>
        {% endif %}
      </h5>
      <p><strong>Created at:</strong> {{ task.datetime }}</p>
      <p style="color:red"><strong>Deadline</strong> {{ task.deadline }}</p>
      <p><strong>Tags:</strong>
        {% for tag in task.tag.all %}
          {{ tag.name }}{% if not forloop.last %}, {% endif %}
        {% empty %}
          <p>No tags</p>
        {% endfor %}
      </p>
      {% if task.is_completed %}
        <form method="post" action="{% url 'core:task-toggle-completion' pk=task.pk action='uncomplete' %}" style="display:inline;">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary mr-1">Undo</button>
        </form>
      {% else %}
        <form method="post" action="{% url 'core:task-toggle-completion' pk=task.pk action='complete' %}" style="display:inline;">
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-success mr-1">✅</button>
        </form>
      {% endif %}
      <a href="{% url 'core:task-update' pk=task.pk %}" class="btn btn-primary mr-1">Update</a>
      <a href="{% url 'core:task-delete' pk=task.pk %}" class="btn btn-danger">Delete</a>
      <br>
    </div>
  {% endfor %}
{% endblock %}

templates/core/tag_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="form-container">
    <h3>Create Tag</h3>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
        <input type="Submit" class="btn btn-success" value="Create">
    </form>
  </div>
{% endblock %}

templates/core/tag_delete.html
{% extends "base.html" %}

{% block content %}
  <h3>Confirm Tag Deletion</h3>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url 'core:tag-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center ml-5 mt-3 mb-3">
    <h1><strong>TAG List</strong></h1>
    <a href="{% url 'core:task-create' %}" class="btn btn-success mr-5">Create new</a>
  </div>
  {% for tag in tags %}
    <div class="ml-5 mt-3 mb-5">
      <p><strong>Name: </strong>{{ tag.name }}</p>
      <a href="{% url 'core:tag-update' pk=tag.pk %}" class="btn btn-primary mr-1">Update</a>
      <a href="{% url 'core:tag-delete' pk=tag.pk %}" class="btn btn-danger">Delete</a>
    </div>
  {% endfor %}
{% endblock %}

templates/core/tag_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="form-container">
    <h3>Update Tag</h3>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
        <input type="Submit" class="btn btn-primary" value="Update">
    </form>
  </div>
{% endblock %}

templates/core/task_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="form-container">
    <h3>Create Task</h3>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
        <input type="Submit" class="btn btn-success" value="Create">
    </form>
  </div>
{% endblock %}

templates/core/task_delete.html
{% extends "base.html" %}

{% block content %}
  <h3>Confirm Task Deletion</h3>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url 'core:index' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/task_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="form-container">
    <h3>Update Task</h3>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
        <input type="Submit" class="btn btn-primary" value="Update">
    </form>
  </div>
{% endblock %}

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'core:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'core:tag-list' %}">Tags</a></li>
</ul>